spring:
  profiles:
    active: local-dev

---
spring.profiles: local-dev
spring:
  profiles:
    include: local-postgresql-credentials, debug, mustuche-attribute-dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stupid-brain-db
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  profiles: local-postgresql-credentials
  datasource:
    username: postgres
    password: password

---
spring:
  profiles: debug
logging:
  level:
    com.pixel.stupidbrain: debug

---
spring:
  profiles: mustuche-attribute-dev
  mustache:
    expose-request-attributes: true